version: "3"
services:
  sql:
    image: albiondata/sql:latest
    restart: on-failure
    command: "-n 'nats://${NATS_USER}:${NATS_PWD}@nats:4222' -s 'server=mysql;port=3306;database=${MYSQL_DB};user=${MYSQL_USER};password=${MYSQL_PWD}' -d"
    depends_on: 
      - mysql
      - nats
    networks: 
      - albiondata
  api:
    image: albiondata/api:latest
    restart: on-failure
    command: "-s 'server=mysql;port=3306;database=${MYSQL_DB};user=${MYSQL_USER};password=${MYSQL_PWD}' -d"
    ports:
      - 8056:80
    depends_on: 
      - mysql
    networks: 
      - albiondata
  gate:
    image: albiondata/gate:latest
    restart: on-failure
    environment:
      ENABLE_NATS: 1
      NATS_URI: nats://${NATS_USER}:${NATS_PWD}@nats:4222
      POW_DIFFICULITY: ${POW_DIFFICULITY:-35}
      POW_PORT: ${POW_PORT:-4223}      
    ports:
      - 4223:4223
    depends_on: 
      - nats
    networks: 
      - albiondata
  deduper:
    image: albiondata/deduper:latest
    restart: on-failure
    command: "-o nats://${NATS_USER}:${NATS_PWD}@nats:4222 -n 'nats://${NATS_USER}:${NATS_PWD}@nats:4222' -r 'redis:6379' -d"
    depends_on: 
      - nats
      - redis
    networks: 
      - albiondata
  nats:
    image: nats
    environment:
      NATS_USER: ${NATS_USER}
      NATS_PWD: ${NATS_PWD}
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    volumes:
      - ./nats/nats-server.conf:/etc/nats/nats-server.conf
    command: "-c /etc/nats/nats-server.conf"
    networks: 
      - albiondata
  mysql:
    image: mariadb:10.5.10
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_PWD}
    ports:
      - 3306:3306
    volumes:
      - ./mysqldata:/var/lib/mysql
      - ./mysqlconfig/70-server.cnf:/etc/mysql/mariadb.conf.d/70-server.cnf
    networks: 
      - albiondata
  mysql-backup:
    image: databack/mysql-backup:latest
    environment:
      DB_SERVER: mysql
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PWD}
      DB_NAMES: ${MYSQL_DB}
      DB_DUMP_FREQ: 1440 # Once a day
      DB_DUMP_BEGIN: 0100 # 01:00am
      DB_DUMP_TARGET: /db
      MYSQLDUMP_OPTS: "--opt --skip-add-drop-database --skip-add-drop-table --replace"
      # DB_DUMP_DEBUG: true
    volumes:
      - "./web/database:/db"
      - "./mysql-backup:/scripts.d"
    depends_on: 
      - mysql
    networks: 
    - albiondata
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redisdata:/data
    command: redis-server --appendonly yes
    networks: 
      - albiondata
  proxy:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    environment:
      X_FRAME_OPTIONS: "sameorigin"
      DB_SQLITE_FILE: "/data/database.sqlite"
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./nginx_proxy_manager/data:/data
      - ./nginx_proxy_manager/letsencrypt:/etc/letsencrypt
    networks: 
      - albiondata
  nginx:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    environment:
      - X_FRAME_OPTIONS="sameorigin"
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./nginx_proxy_manager/data:/data
      - ./nginx_proxy_manager/letsencrypt:/etc/letsencrypt
    networks: 
      - albiondata
  nginx:
    image: nginx
    volumes:
      - "$PWD/web:/usr/share/nginx/html:ro"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - 8080:80        
networks:
  albiondata: